version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: hibinka-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - hibinka-network

  server:
    image: gakombarov/hibinka-server:latest
    container_name: hibinka-server
    restart: always
    build:
      context: ./hibinka51-server
      dockerfile: Dockerfile.server
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - hibinka-network

  client:
    image: gakombarov/hibinka-client:latest
    container_name: hibinka-client
    restart: always
    build:
      context: ./hibinka51-client
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - hibinka-network

networks:
  hibinka-network:
    driver: bridge

volumes:
  postgres_data:
