FROM mcr.microsoft.com/devcontainers/python:1-3.11-bookworm

USER root

RUN echo "deb http://mirror.yandex.ru/debian/ bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list && \
    echo "deb http://mirror.yandex.ru/debian/ bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb http://mirror.yandex.ru/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list 

RUN rm -f /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources

RUN apt-get update --fix-missing && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y --no-install-recommends \
       gcc \
       libpq-dev \
       curl \
       xz-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN curl -fsSLO https://npmmirror.com/mirrors/node/v22.13.1/node-v22.13.1-linux-x64.tar.xz \
    && tar -xJf node-v22.13.1-linux-x64.tar.xz -C /usr/local --strip-components=1 \
    && rm node-v22.13.1-linux-x64.tar.xz

WORKDIR /workspace