"""

Revision ID: 0fa17a53c3ed
Revises: 52c01776e12f
Create Date: 2026-05-07 10:05:41.905419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa17a53c3ed'
down_revision: Union[str, None] = '52c01776e12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('vehicles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Soft delete flag')
    op.alter_column('vehicles', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the record',
               existing_nullable=False)
    op.drop_constraint('vehicles_license_plate_key', 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.create_unique_constraint('vehicles_license_plate_key', 'vehicles', ['license_plate'])
    op.alter_column('vehicles', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('vehicles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Soft delete flag')
    op.alter_column('vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
