"""

Revision ID: 21d8d765b070
Revises: 3055f7038cac
Create Date: 2026-05-13 10:44:32.080425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d8d765b070'
down_revision: Union[str, None] = '3055f7038cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scheduled_trip_cycles_schedule_id_fkey', 'scheduled_trip_cycles', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_trip_cycles', 'scheduled_trips', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('scheduled_trip_stops_schedule_id_fkey', 'scheduled_trip_stops', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_trip_stops', 'scheduled_trips', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('trips_scheduled_trip_id_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'scheduled_trips', ['scheduled_trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_scheduled_trip_id_fkey', 'trips', 'scheduled_trips', ['scheduled_trip_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'scheduled_trip_stops', type_='foreignkey')
    op.create_foreign_key('scheduled_trip_stops_schedule_id_fkey', 'scheduled_trip_stops', 'scheduled_trips', ['schedule_id'], ['id'])
    op.drop_constraint(None, 'scheduled_trip_cycles', type_='foreignkey')
    op.create_foreign_key('scheduled_trip_cycles_schedule_id_fkey', 'scheduled_trip_cycles', 'scheduled_trips', ['schedule_id'], ['id'])
    # ### end Alembic commands ###
