"""

Revision ID: 3055f7038cac
Revises: 414d43a778d9
Create Date: 2026-05-13 10:24:57.922157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3055f7038cac'
down_revision: Union[str, None] = '414d43a778d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_trip_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('days_of_week', sa.String(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('return_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['scheduled_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scheduled_trip_stops', sa.Column('schedule_id', sa.UUID(), nullable=True))
    op.alter_column('scheduled_trip_stops', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('scheduled_trip_stops', 'location',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Название остановки',
               existing_nullable=False)
    op.alter_column('scheduled_trip_stops', 'stop_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Время прибытия на остановку',
               existing_nullable=True)
    op.alter_column('scheduled_trip_stops', 'stop_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Порядковый номер остановки')
    op.alter_column('scheduled_trip_stops', 'description',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Описание (например 'У магазина')",
               existing_nullable=True)
    op.drop_index('ix_scheduled_trip_stops_id', table_name='scheduled_trip_stops')
    op.drop_constraint('scheduled_trip_stops_trip_id_fkey', 'scheduled_trip_stops', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_trip_stops', 'scheduled_trips', ['schedule_id'], ['id'])
    op.drop_column('scheduled_trip_stops', 'deleted_at')
    op.drop_column('scheduled_trip_stops', 'trip_id')
    op.drop_column('scheduled_trip_stops', 'created_at')
    op.drop_column('scheduled_trip_stops', 'is_deleted')
    op.drop_column('scheduled_trip_stops', 'updated_at')
    op.add_column('scheduled_trips', sa.Column('client_name', sa.String(), nullable=True))
    op.alter_column('scheduled_trips', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('scheduled_trips', 'route_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Номер маршрута',
               existing_nullable=False)
    op.alter_column('scheduled_trips', 'departure_location',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Место отправления',
               existing_nullable=False)
    op.alter_column('scheduled_trips', 'destination',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Место назначения',
               existing_nullable=False)
    op.alter_column('scheduled_trips', 'total_contract_value',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Общая сумма контракта')
    op.alter_column('scheduled_trips', 'contract_start_date',
               existing_type=sa.DATE(),
               nullable=False,
               comment=None,
               existing_comment='Дата начала контракта')
    op.alter_column('scheduled_trips', 'contract_end_date',
               existing_type=sa.DATE(),
               nullable=False,
               comment=None,
               existing_comment='Дата окончания действия расписания/контракта')
    op.alter_column('scheduled_trips', 'price',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Стоимость проезда')
    op.alter_column('scheduled_trips', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Показывать ли рейс на сайте',
               existing_nullable=True)
    op.alter_column('scheduled_trips', 'show_on_landing',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Показывать на лендинге как инфо',
               existing_nullable=True)
    op.alter_column('scheduled_trips', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment=None,
               existing_comment='Заметки',
               existing_nullable=True)
    op.drop_index('ix_scheduled_trips_id', table_name='scheduled_trips')
    op.drop_column('scheduled_trips', 'deleted_at')
    op.drop_column('scheduled_trips', 'updated_at')
    op.drop_column('scheduled_trips', 'days_of_week')
    op.drop_column('scheduled_trips', 'is_deleted')
    op.drop_column('scheduled_trips', 'created_at')
    op.drop_column('scheduled_trips', 'departure_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_trips', sa.Column('departure_time', postgresql.TIME(), autoincrement=False, nullable=False, comment='Время отправления из начальной точки'))
    op.add_column('scheduled_trips', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp when the record was created'))
    op.add_column('scheduled_trips', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Soft delete flag'))
    op.add_column('scheduled_trips', sa.Column('days_of_week', sa.VARCHAR(), autoincrement=False, nullable=False, comment="Дни недели (строкой, например 'Пн, Ср, Пт')"))
    op.add_column('scheduled_trips', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp when the record was last updated'))
    op.add_column('scheduled_trips', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp when the record was deleted'))
    op.create_index('ix_scheduled_trips_id', 'scheduled_trips', ['id'], unique=False)
    op.alter_column('scheduled_trips', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment='Заметки',
               existing_nullable=True)
    op.alter_column('scheduled_trips', 'show_on_landing',
               existing_type=sa.BOOLEAN(),
               comment='Показывать на лендинге как инфо',
               existing_nullable=True)
    op.alter_column('scheduled_trips', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Показывать ли рейс на сайте',
               existing_nullable=True)
    op.alter_column('scheduled_trips', 'price',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Стоимость проезда')
    op.alter_column('scheduled_trips', 'contract_end_date',
               existing_type=sa.DATE(),
               nullable=True,
               comment='Дата окончания действия расписания/контракта')
    op.alter_column('scheduled_trips', 'contract_start_date',
               existing_type=sa.DATE(),
               nullable=True,
               comment='Дата начала контракта')
    op.alter_column('scheduled_trips', 'total_contract_value',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Общая сумма контракта')
    op.alter_column('scheduled_trips', 'destination',
               existing_type=sa.VARCHAR(),
               comment='Место назначения',
               existing_nullable=False)
    op.alter_column('scheduled_trips', 'departure_location',
               existing_type=sa.VARCHAR(),
               comment='Место отправления',
               existing_nullable=False)
    op.alter_column('scheduled_trips', 'route_number',
               existing_type=sa.INTEGER(),
               comment='Номер маршрута',
               existing_nullable=False)
    op.alter_column('scheduled_trips', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the record',
               existing_nullable=False)
    op.drop_column('scheduled_trips', 'client_name')
    op.add_column('scheduled_trip_stops', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp when the record was last updated'))
    op.add_column('scheduled_trip_stops', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Soft delete flag'))
    op.add_column('scheduled_trip_stops', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp when the record was created'))
    op.add_column('scheduled_trip_stops', sa.Column('trip_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('scheduled_trip_stops', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp when the record was deleted'))
    op.drop_constraint(None, 'scheduled_trip_stops', type_='foreignkey')
    op.create_foreign_key('scheduled_trip_stops_trip_id_fkey', 'scheduled_trip_stops', 'scheduled_trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_scheduled_trip_stops_id', 'scheduled_trip_stops', ['id'], unique=False)
    op.alter_column('scheduled_trip_stops', 'description',
               existing_type=sa.VARCHAR(),
               comment="Описание (например 'У магазина')",
               existing_nullable=True)
    op.alter_column('scheduled_trip_stops', 'stop_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Порядковый номер остановки')
    op.alter_column('scheduled_trip_stops', 'stop_time',
               existing_type=postgresql.TIME(),
               comment='Время прибытия на остановку',
               existing_nullable=True)
    op.alter_column('scheduled_trip_stops', 'location',
               existing_type=sa.VARCHAR(),
               comment='Название остановки',
               existing_nullable=False)
    op.alter_column('scheduled_trip_stops', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the record',
               existing_nullable=False)
    op.drop_column('scheduled_trip_stops', 'schedule_id')
    op.drop_table('scheduled_trip_cycles')
    # ### end Alembic commands ###
