"""

Revision ID: 36ca2c7576d8
Revises: e4f0ac3f3c1d
Create Date: 2026-05-07 11:23:40.512700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36ca2c7576d8'
down_revision: Union[str, None] = 'e4f0ac3f3c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('vehicles', 'alias',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vehicles', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_vehicles_id', table_name='vehicles')
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'deleted_at')
    op.drop_column('vehicles', 'is_deleted')
    op.drop_column('vehicles', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp when the record was created'))
    op.add_column('vehicles', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Soft delete flag'))
    op.add_column('vehicles', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp when the record was deleted'))
    op.add_column('vehicles', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp when the record was last updated'))
    op.create_index('ix_vehicles_id', 'vehicles', ['id'], unique=False)
    op.alter_column('vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('vehicles', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vehicles', 'alias',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vehicles', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the record',
               existing_nullable=False)
    # ### end Alembic commands ###
