"""

Revision ID: 3995747e12e3
Revises: 09b2b31def80
Create Date: 2026-05-07 18:06:02.515969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3995747e12e3'
down_revision: Union[str, None] = '09b2b31def80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when the record was deleted',
               existing_nullable=True)
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when the record was created',
               existing_nullable=False)
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when the record was last updated',
               existing_nullable=False)
    op.drop_index('ix_vehicles_license_plate', table_name='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vehicles_license_plate', 'vehicles', ['license_plate'], unique=True)
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=False)
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when the record was created',
               existing_nullable=False)
    op.alter_column('vehicles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when the record was deleted',
               existing_nullable=True)
    # ### end Alembic commands ###
