"""

Revision ID: 3d210d2376ad
Revises: ce28ffa3705c
Create Date: 2026-05-18 08:48:57.581714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d210d2376ad'
down_revision: Union[str, None] = 'ce28ffa3705c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trips_driver_id_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'driver_profiles', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_driver_id_fkey', 'trips', 'users', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
