"""

Revision ID: 72c100359fb8
Revises: 8126305b3a88
Create Date: 2026-05-18 08:25:25.633094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c100359fb8'
down_revision: Union[str, None] = '8126305b3a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'trips', 'users', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'driver_id')
    # ### end Alembic commands ###
