"""add_finances_to_booking_and_trip

Revision ID: 7812278ab8bc
Revises: 8929adee4d15
Create Date: 2026-03-29 15:26:52.503398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7812278ab8bc'
down_revision: Union[str, None] = '8929adee4d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Итого'))
    op.add_column('bookings', sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Выплачено'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'paid_amount')
    op.drop_column('bookings', 'total_amount')
    # ### end Alembic commands ###
