"""

Revision ID: 7886955567c4
Revises: 36ca2c7576d8
Create Date: 2026-05-07 11:27:04.874456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7886955567c4'
down_revision: Union[str, None] = '36ca2c7576d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trips_vehicle_id_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_vehicle_id_fkey', 'trips', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
