"""Add scheduled trips with stops

Revision ID: 8929adee4d15
Revises: a74a83160898
Create Date: 2026-02-15 06:49:14.189118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8929adee4d15'
down_revision: Union[str, None] = 'a74a83160898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_trips',
    sa.Column('route_number', sa.Integer(), nullable=False, comment='Номер маршрута'),
    sa.Column('departure_location', sa.String(), nullable=False, comment='Место отправления'),
    sa.Column('destination', sa.String(), nullable=False, comment='Место назначения'),
    sa.Column('days_of_week', sa.String(), nullable=False, comment="Дни недели (строкой, например 'Пн, Ср, Пт')"),
    sa.Column('departure_time', sa.Time(), nullable=False, comment='Время отправления из начальной точки'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Стоимость проезда'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Показывать ли рейс на сайте'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Заметки'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_trips_id'), 'scheduled_trips', ['id'], unique=False)
    op.create_table('scheduled_trip_stops',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False, comment='Порядковый номер остановки'),
    sa.Column('location', sa.String(), nullable=False, comment='Название остановки'),
    sa.Column('stop_time', sa.Time(), nullable=True, comment='Время прибытия на остановку'),
    sa.Column('description', sa.String(), nullable=True, comment="Описание (например 'У магазина')"),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['trip_id'], ['scheduled_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_trip_stops_id'), 'scheduled_trip_stops', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_trip_stops_id'), table_name='scheduled_trip_stops')
    op.drop_table('scheduled_trip_stops')
    op.drop_index(op.f('ix_scheduled_trips_id'), table_name='scheduled_trips')
    op.drop_table('scheduled_trips')
    # ### end Alembic commands ###
