"""

Revision ID: 9979d4b22a04
Revises: 21d8d765b070
Create Date: 2026-05-13 11:10:46.848513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9979d4b22a04'
down_revision: Union[str, None] = '21d8d765b070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_stops', sa.Column('stop_time', sa.Time(), nullable=True, comment='Время прибытия на остановку'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_stops', 'stop_time')
    # ### end Alembic commands ###
