"""add booking model

Revision ID: a74a83160898
Revises: 30d4b2a22f91
Create Date: 2026-02-14 16:13:43.109748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74a83160898'
down_revision: Union[str, None] = '30d4b2a22f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='Клиент сделавший бронирование'),
    sa.Column('source', sa.Enum('PHONE', 'EMAIL', 'WEBSITE', 'MESSENGER', name='bookingsource'), nullable=False, comment='Источник заявки'),
    sa.Column('desired_trip_date', sa.Date(), nullable=False, comment='Дата когда клиент хочет совершить поездку'),
    sa.Column('desired_departure_time', sa.Time(), nullable=False, comment='Время отправления по желанию клиента'),
    sa.Column('desired_trip_location', sa.String(length=255), nullable=False, comment='Адрес или название пункта отправления'),
    sa.Column('arrival_location', sa.String(length=255), nullable=False, comment='Адрес или название пункта назначения'),
    sa.Column('passenger_count', sa.Integer(), nullable=False, comment='Сколько человек планируют поездку'),
    sa.Column('luggage_description', sa.Text(), nullable=True, comment='Информация о количестве и типе багажа'),
    sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='Дополнительные заметки и пожелания'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
