"""

Revision ID: aa39eb141f9b
Revises: 431eb91b828e
Create Date: 2026-05-11 09:22:19.951352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa39eb141f9b'
down_revision: Union[str, None] = '431eb91b828e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_trips', sa.Column('contract_start_date', sa.Date(), nullable=True, comment='Дата начала контракта'))
    op.add_column('scheduled_trips', sa.Column('total_contract_value', sa.Integer(), nullable=True, comment='Общая сумма контракта'))
    op.add_column('scheduled_trips', sa.Column('show_on_landing', sa.Boolean(), nullable=True, comment='Показывать на лендинге как инфо'))
    op.add_column('scheduled_trips', sa.Column('contract_end_date', sa.Date(), nullable=True, comment='Дата окончания действия расписания/контракта'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_trips', 'contract_end_date')
    op.drop_column('scheduled_trips', 'show_on_landing')
    op.drop_column('scheduled_trips', 'total_contract_value')
    op.drop_column('scheduled_trips', 'contract_start_date')
    # ### end Alembic commands ###
