"""create vehicles table

Revision ID: ae35d732c64d
Revises: bc527cad7ed9
Create Date: 2026-04-22 11:36:34.794942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae35d732c64d'
down_revision: Union[str, None] = 'bc527cad7ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
