"""create vehicles table

Revision ID: bc527cad7ed9
Revises: 273a790bc5be
Create Date: 2026-04-22 11:20:30.463980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc527cad7ed9'
down_revision: Union[str, None] = '273a790bc5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('BUS', 'MINIBUS', name='vehiclecategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
