"""add trips table

Revision ID: bc5f5a57ed8b
Revises: 55af0dc7b27e
Create Date: 2026-03-29 15:49:49.887576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5f5a57ed8b'
down_revision: Union[str, None] = '55af0dc7b27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('scheduled_trip_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('trip_date', sa.Date(), nullable=False, comment='Дата поездки'),
    sa.Column('departure_time', sa.Time(), nullable=False, comment='Время старта'),
    sa.Column('departure_location', sa.String(length=255), nullable=False),
    sa.Column('arrival_location', sa.String(length=255), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False, comment='Количество пассжаиров'),
    sa.Column('is_regular', sa.Boolean(), nullable=True, comment='Это регулярный маршрут (госконтракт)?'),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('luggage_description', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('show_on_landing', sa.Boolean(), nullable=False, comment='Показывать ли поездку на сайте'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('trip_stops',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_stops_id'), 'trip_stops', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_stops_id'), table_name='trip_stops')
    op.drop_table('trip_stops')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
