"""initial_schema

Revision ID: c2c219b196b1
Revises: 
Create Date: 2026-04-26 08:41:58.091859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c219b196b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_trips',
    sa.Column('route_number', sa.Integer(), nullable=False, comment='Номер маршрута'),
    sa.Column('departure_location', sa.String(), nullable=False, comment='Место отправления'),
    sa.Column('destination', sa.String(), nullable=False, comment='Место назначения'),
    sa.Column('days_of_week', sa.String(), nullable=False, comment="Дни недели (строкой, например 'Пн, Ср, Пт')"),
    sa.Column('departure_time', sa.Time(), nullable=False, comment='Время отправления из начальной точки'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Стоимость проезда'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Показывать ли рейс на сайте'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Заметки'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_trips_id'), 'scheduled_trips', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True, comment='Path to avatar image'),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('account_type', sa.Enum('ADMIN', 'DRIVER', 'CUSTOMER', name='userrole'), nullable=False, comment='User role (ADMIN, DRIVER, CUSTOMER)'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('BUS', 'MINIBUS', name='vehiclecategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='Клиент сделавший бронирование'),
    sa.Column('source', sa.Enum('PHONE', 'EMAIL', 'WEBSITE', 'MESSENGER', name='bookingsource'), nullable=False, comment='Источник заявки'),
    sa.Column('desired_trip_date', sa.Date(), nullable=False, comment='Дата поездки'),
    sa.Column('desired_departure_time', sa.Time(), nullable=False, comment='Время отправления'),
    sa.Column('desired_trip_location', sa.String(length=255), nullable=False, comment='Откуда'),
    sa.Column('arrival_location', sa.String(length=255), nullable=False, comment='Куда'),
    sa.Column('is_round_trip', sa.Boolean(), server_default='false', nullable=False, comment='Обратный рейс'),
    sa.Column('return_date', sa.Date(), nullable=True, comment='Дата обратной поездки'),
    sa.Column('return_time', sa.Time(), nullable=True, comment='Время обратной поездки'),
    sa.Column('passenger_count', sa.Integer(), nullable=False, comment='Сколько всего человек'),
    sa.Column('luggage_description', sa.Text(), nullable=True, comment='Багаж'),
    sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='Заметки'),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Итого к оплате'),
    sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Выплачено'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('scheduled_trip_stops',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False, comment='Порядковый номер остановки'),
    sa.Column('location', sa.String(), nullable=False, comment='Название остановки'),
    sa.Column('stop_time', sa.Time(), nullable=True, comment='Время прибытия на остановку'),
    sa.Column('description', sa.String(), nullable=True, comment="Описание (например 'У магазина')"),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['trip_id'], ['scheduled_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_trip_stops_id'), 'scheduled_trip_stops', ['id'], unique=False)
    op.create_table('trips',
    sa.Column('scheduled_trip_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True, comment='Заявка, к которой привязана поездка'),
    sa.Column('trip_date', sa.Date(), nullable=False, comment='Дата поездки'),
    sa.Column('departure_time', sa.Time(), nullable=False, comment='Время старта'),
    sa.Column('departure_location', sa.String(length=255), nullable=False),
    sa.Column('arrival_location', sa.String(length=255), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False, comment='Количество пассажиров в авто'),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Итого к оплате за поездку'),
    sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Выплаченная сумма'),
    sa.Column('is_regular', sa.Boolean(), nullable=True, comment='Регулярный маршрут?'),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('show_on_landing', sa.Boolean(), nullable=False, comment='Показывать на сайте'),
    sa.Column('has_trailer', sa.Boolean(), server_default='false', nullable=False, comment='Необходим ли прицеп'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('trip_stops',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_stops_id'), 'trip_stops', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_stops_id'), table_name='trip_stops')
    op.drop_table('trip_stops')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_scheduled_trip_stops_id'), table_name='scheduled_trip_stops')
    op.drop_table('scheduled_trip_stops')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduled_trips_id'), table_name='scheduled_trips')
    op.drop_table('scheduled_trips')
    # ### end Alembic commands ###
