"""add_trip_finances

Revision ID: d1171a29a922
Revises: d24ad0cf5108
Create Date: 2026-04-24 10:05:19.224829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1171a29a922'
down_revision: Union[str, None] = 'd24ad0cf5108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Итого к оплате за поездку'))
    op.add_column('trips', sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Выплаченная сумма'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'paid_amount')
    op.drop_column('trips', 'total_amount')
    # ### end Alembic commands ###
