"""add_round_trip_and_finances_fix

Revision ID: d24ad0cf5108
Revises: bc5f5a57ed8b
Create Date: 2026-04-05 11:26:29.621520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd24ad0cf5108'
down_revision: Union[str, None] = 'bc5f5a57ed8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_round_trip', sa.Boolean(), server_default='false', nullable=False, comment='Обратный рейс'))
    op.add_column('bookings', sa.Column('return_date', sa.Date(), nullable=True, comment='Дата обратной поездки'))
    op.add_column('bookings', sa.Column('return_time', sa.Time(), nullable=True, comment='Время обратной поездки'))
    op.alter_column('bookings', 'desired_trip_date',
               existing_type=sa.DATE(),
               comment='Дата поездки',
               existing_comment='Дата когда клиент хочет совершить поездку',
               existing_nullable=False)
    op.alter_column('bookings', 'desired_departure_time',
               existing_type=postgresql.TIME(),
               comment='Время отправления',
               existing_comment='Время отправления по желанию клиента',
               existing_nullable=False)
    op.alter_column('bookings', 'desired_trip_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Откуда',
               existing_comment='Адрес или название пункта отправления',
               existing_nullable=False)
    op.alter_column('bookings', 'arrival_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Куда',
               existing_comment='Адрес или название пункта назначения',
               existing_nullable=False)
    op.alter_column('bookings', 'passenger_count',
               existing_type=sa.INTEGER(),
               comment='Сколько всего человек',
               existing_comment='Сколько человек планируют поездку',
               existing_nullable=False)
    op.alter_column('bookings', 'luggage_description',
               existing_type=sa.TEXT(),
               comment='Багаж',
               existing_comment='Информация о количестве и типе багажа',
               existing_nullable=True)
    op.alter_column('bookings', 'notes',
               existing_type=sa.TEXT(),
               comment='Заметки',
               existing_comment='Дополнительные заметки и пожелания',
               existing_nullable=True)
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Итого к оплате',
               existing_comment='Итого',
               existing_nullable=True)
    op.add_column('trips', sa.Column('booking_id', sa.UUID(), nullable=True, comment='Заявка, к которой привязана поездка'))
    op.add_column('trips', sa.Column('has_trailer', sa.Boolean(), server_default='false', nullable=False, comment='Необходим ли прицеп'))
    op.alter_column('trips', 'passenger_count',
               existing_type=sa.INTEGER(),
               comment='Количество пассажиров в авто',
               existing_comment='Количество пассжаиров',
               existing_nullable=False)
    op.alter_column('trips', 'is_regular',
               existing_type=sa.BOOLEAN(),
               comment='Регулярный маршрут?',
               existing_comment='Это регулярный маршрут (госконтракт)?',
               existing_nullable=True)
    op.alter_column('trips', 'show_on_landing',
               existing_type=sa.BOOLEAN(),
               comment='Показывать на сайте',
               existing_comment='Показывать ли поездку на сайте',
               existing_nullable=False)
    op.create_foreign_key(None, 'trips', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trips', 'luggage_description')
    op.drop_column('trips', 'total_amount')
    op.drop_column('trips', 'paid_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('paid_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('luggage_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.alter_column('trips', 'show_on_landing',
               existing_type=sa.BOOLEAN(),
               comment='Показывать ли поездку на сайте',
               existing_comment='Показывать на сайте',
               existing_nullable=False)
    op.alter_column('trips', 'is_regular',
               existing_type=sa.BOOLEAN(),
               comment='Это регулярный маршрут (госконтракт)?',
               existing_comment='Регулярный маршрут?',
               existing_nullable=True)
    op.alter_column('trips', 'passenger_count',
               existing_type=sa.INTEGER(),
               comment='Количество пассжаиров',
               existing_comment='Количество пассажиров в авто',
               existing_nullable=False)
    op.drop_column('trips', 'has_trailer')
    op.drop_column('trips', 'booking_id')
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Итого',
               existing_comment='Итого к оплате',
               existing_nullable=True)
    op.alter_column('bookings', 'notes',
               existing_type=sa.TEXT(),
               comment='Дополнительные заметки и пожелания',
               existing_comment='Заметки',
               existing_nullable=True)
    op.alter_column('bookings', 'luggage_description',
               existing_type=sa.TEXT(),
               comment='Информация о количестве и типе багажа',
               existing_comment='Багаж',
               existing_nullable=True)
    op.alter_column('bookings', 'passenger_count',
               existing_type=sa.INTEGER(),
               comment='Сколько человек планируют поездку',
               existing_comment='Сколько всего человек',
               existing_nullable=False)
    op.alter_column('bookings', 'arrival_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Адрес или название пункта назначения',
               existing_comment='Куда',
               existing_nullable=False)
    op.alter_column('bookings', 'desired_trip_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Адрес или название пункта отправления',
               existing_comment='Откуда',
               existing_nullable=False)
    op.alter_column('bookings', 'desired_departure_time',
               existing_type=postgresql.TIME(),
               comment='Время отправления по желанию клиента',
               existing_comment='Время отправления',
               existing_nullable=False)
    op.alter_column('bookings', 'desired_trip_date',
               existing_type=sa.DATE(),
               comment='Дата когда клиент хочет совершить поездку',
               existing_comment='Дата поездки',
               existing_nullable=False)
    op.drop_column('bookings', 'return_time')
    op.drop_column('bookings', 'return_date')
    op.drop_column('bookings', 'is_round_trip')
    # ### end Alembic commands ###
