"""update_trips

Revision ID: e3e72d99c467
Revises: 2bf6264e7173
Create Date: 2026-04-27 11:47:05.780477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3e72d99c467'
down_revision: Union[str, None] = '2bf6264e7173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_profiles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('driver_profiles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when the record was deleted',
               existing_nullable=True)
    op.alter_column('driver_profiles', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('driver_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when the record was created',
               existing_nullable=False)
    op.alter_column('driver_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when the record was last updated',
               existing_nullable=False)
    op.drop_constraint('driver_profiles_phone_key', 'driver_profiles', type_='unique')
    op.add_column('trips', sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Итого к оплате за поездку'))
    op.add_column('trips', sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Выплаченная сумма'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'paid_amount')
    op.drop_column('trips', 'total_amount')
    op.create_unique_constraint('driver_profiles_phone_key', 'driver_profiles', ['phone'])
    op.alter_column('driver_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=False)
    op.alter_column('driver_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when the record was created',
               existing_nullable=False)
    op.alter_column('driver_profiles', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the record',
               existing_nullable=False)
    op.alter_column('driver_profiles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when the record was deleted',
               existing_nullable=True)
    op.alter_column('driver_profiles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
