name: Deploy to Production VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Execute deployment script via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd hibinka-app

            git pull origin main 
            docker-compose -f docker-compose.prod.yml build --no-cache client
            docker-compose -f docker-compose.prod.yml up -d --force-recreate server client
            docker image prune -f
